---
- name: Plays for master node
  hosts: tag_Name_Master_node_0, tag_Name_Master_node_1, tag_Name_Master_node_2
  user: ubuntu
  become: yes
  tasks:
    - name: Create /var/lib/kubernetes
      ansible.builtin.file:
        path: /var/lib/kubernetes
        state: directory
        follow: yes

    - name: Copy certificates and configuration files 
      copy:
        src: "/tmp/ca-authority/{{ item }}"
        dest: /var/lib/kubernetes
        remote_src: no
      loop:
        - ca.pem
        - ca-key.pem
        - service-account-key.pem
        - service-account.pem
        - master-kubernetes.pem
        - master-kubernetes-key.pem
        - kube-scheduler.kubeconfig
        - kube-controller-manager.kubeconfig
        - encryption-config.yaml